; PlatformIO Project Configuration File

[env:esp32pico]
platform = espressif32
framework = espidf
board = esp32dev

monitor_speed = 115200

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror
    -fno-exceptions
    -I app/include
    -I app/src
    -I mid/ble
    -I mid/i2c
    -I mid/spi
    -I mid/ina
    -I config
    -I test/unit
    -I lib
    -I lib/Bus
    -I lib/Devices
    -I lib/Devices/INA237

build_src_filter =
    +<src/>
    +<app/src/>
    +<mid/ble/>
    +<mid/i2c/>
    +<mid/spi/>
    +<mid/ina/>
    +<lib/>
    +<lib/Bus/>
    +<lib/Devices/>
    +<lib/Devices/INA237/>

build_unflags =
    -fno-rtti